[mypy]
python_version = 3.10
plugins = mypy_django_plugin.main
strict = true
warn_return_any = true
warn_unused_configs = true
namespace_packages = true
explicit_package_bases = true
mypy_path = src

[mypy.plugins.django-stubs]
django_settings_module = tests.conftest

[mypy-apcore.*]
ignore_missing_imports = True

[mypy-apcore_mcp.*]
ignore_missing_imports = True

[mypy-ninja.*]
ignore_missing_imports = True
